### ISSUE TITLE
App started crashing

### ISSUE THREAD

**Issue by abdullah353** [janpieterz/koajs-static-folder#8]
After adding the asset package as following.
```js
const serve = require('koa-static-folder')
const app = new Koa()
app.use(serve('./public'))
```

I have started receiving the following error on page refresh.

```
internal/streams/destroy.js:12
      cb(err);
      ^

TypeError: cb is not a function
    at ReadStream.destroy (internal/streams/destroy.js:12:7)
    at listener (/Users/XAM/liimex/portfolio/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/XAM/liimex/portfolio/node_modules/on-finished/index.js:100:5)
    at callback (/Users/XAM/liimex/portfolio/node_modules/ee-first/index.js:55:10)
    at ServerResponse.onevent (/Users/XAM/liimex/portfolio/node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:110:20)
    at ServerResponse.emit (events.js:207:7)
    at onFinish (_http_outgoing.js:733:10)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Also their is this warning when i start the server.
```
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md
```

**Comment by janpieterz** [comment]
Hi @mabdullah353 

Are you using this with koa v2?
If so, we're indeed not setup to handle V2, and I haven't worked a lot with node/koa lately.

**Comment by abdullah353** [comment]
yes i am using "koa": "2.3.0".

**Comment by anwarkh** [comment]
Hello, any new news about this issue ? I have the same problem.

**Comment by janpieterz** [comment]
@anwarkh no news! I'm not using koa/node anymore so difficult to get it going again. I'm open for a pull request though.
